# Generated by Django 6.0.4 on 2026-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='sync_error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='sync_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('already_synced', 'Already Synced'), ('contact_limit', 'Contact Limit'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
