# Generated by Django 6.0.4 on 2026-06-04 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogo',
            name='logo',
            field=models.FileField(upload_to='clients/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
