# Generated by Django 6.0.4 on 2026-04-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='behance_url',
            field=models.URLField(blank=True, help_text='Optional link to this project on Behance. Falls back to the agency Behance profile when empty.', max_length=500),
        ),
        migrations.CreateModel(
            name='ProjectScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
