# Generated by Django 6.0.4 on 2026-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_behance_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube URL for video projects (youtube.com or youtu.be).', max_length=500),
        ),
    ]
